version: 2
jobs:
  build:
  
    working_directory: ~/circleci-java-spring
    
      docker:
        - image: circleci/openjdk:8-jdk-browsers
        
      steps:   
        - checkout
        - run: echo "A first hellooo"
