version: 2
jobs:
  build:
      
      docker:
        - image: circleci/openjdk:8-jdk-browsers
        
      steps:   
        - checkout
        - run: echo "A first hello"
        
        - run: mvn dependency:go-offline
      
        - save_cache:
            paths:
              - ~/.m2
            key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

        - run: mvn package

        - store_test_results:
            path: target/surefire-reports
